spring:
  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/wordstealer
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    initialization-mode: always
    continue-on-error: true